credentials:
  system:
    domainCredentials:
    - credentials:
      - aws:
          accessKey: "${ACCESS_KEY}"
          id: "aws"
          scope: GLOBAL
          secretKey: "${SECRET_KEY}"
jenkins:
  securityRealm:
    github:
      clientID: "${GITHUB_CLIENT}"
      clientSecret: "${GITHUB_SECRET}"
      githubApiUri: "https://api.github.com"
      githubWebUri: "https://github.com"
      oauthScopes: "read:org,user:email,repo"

  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    github:
      adminUserNames: "MancunianSam"
      allowAnonymousJobStatusPermission: false
      allowAnonymousReadPermission: false
      allowCcTrayPermission: true
      allowGithubWebHookPermission: true
      authenticatedUserCreateJobPermission: false
      authenticatedUserReadPermission: true
      organizationNames: "nationalarchives"
      useRepositoryPermissions: true
  clouds:
  - ecs:
      allowedOverrides: "all"
      cluster: "${JENKINS_CLUSTER}"
      jenkinsUrl: "${LOAD_BALANCER_URL}"
      credentialsId: "aws"
      name: "ecs"
      regionName: "eu-west-1"
      templates:
      - assignPublicIp: true
        cpu: 2048
        image: "nationalarchives/jenkins-sbt-slave"
        label: "ecs"
        launchType: "FARGATE"
        memory: 0
        memoryReservation: 4096
        networkMode: "awsvpc"
        privileged: false
        remoteFSRoot: "/home/jenkins"
        securityGroups: "${FARGATE_SECURITY_GROUP}"
        sharedMemorySize: 0
        subnets: "${FARGATE_SUBNET}"
        templateName: "ecs"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  markupFormatter: "plainText"
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"

unclassified:
  buildStepOperation:
    enabled: false
  gitHubPluginConfig:
    hookUrl: "https://jenkins.tdr-prototype.co.uk"
  gitSCM:
    createAccountBasedOnEmail: false
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "https://jenkins.tdr-prototype.co.uk"
  mailer:
    adminAddress: "address not configured yet <nobody@nowhere>"
    charset: "UTF-8"
    useSsl: false
  pollSCM:
    pollingThreadCount: 10
  timestamperConfig:
    allPipelines: true
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
